### ISSUE TITLE
Credentials leak in the Public

### ISSUE THREAD

**Issue by L3thal14** [canaryGrapher/wearemist_v2#3]
Description:

Credentials leak through a .env file in earlier commits leads to an attacker getting access to the whole MongoDB Atlas as well as the admin email address, MS teams ID, and password.

Impact:

The attacker can establish a connection to the MongoDB cluster in the backend and perform CRUD operations. Since, the backend API fetches news, team info, club news, etc. from the database, this would basically mean a temporary takeover of the website. The form on the website on submission captures the visitor’s IP address and blacklists it for around 6 hours before allowing the form to be refilled. Since the attacker has access to the “blacklist” collection, an automated script that clears that collection after every attempt could lead to spamming the inbox of a legitimate user. The email address and password leak can lead to the complete takeover of the MongoDB account and affect the overall functioning of the club activities(I didn't try signing in).

Steps to Fix:

1. Squash the [commit](https://github.com/canaryGrapher/wearemist_v2/commit/82e75b6ee3be0e561cf9ba95a16dd04c0bf57006) with a later one.
2. In MongoDB Atlas, change the Database access rules to allow only the Frontend deployed server to connect and blacklist other IPs.

**Comment by canaryGrapher** [comment]
Hey! Thanks for the heads up. I have raised an issue with GitHub Support to clear the repository's cached views. I have made the repo private for the time being and will make it public after the issue has been resolved.

**Comment by L3thal14** [comment]
Happy to help :)
